steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['pull', 'alpine']

# Put artifacts on GCS
artifacts:
  objects:
    location: gs://broad-nextstrain-inputs/${REPO_NAME}/${BRANCH_NAME}/${SHORT_SHA}
    paths:  [ '*/*' ]
